In [1]:
import numpy as np

# 1 Задание
Создайте numpy array с элементами от числа N до 0
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
n = 15
x = np.arange(0, n)
a = np.sort(x)[::-1]
a

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# 2 Задание
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
s = np.diag(a, k=0) # Использована переменная a из вернего примера, 
                          # в которой отсортирована сгенерированная последовательность чисел от a до 0
    
s

array([[14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0

In [4]:
print('Сумма значений на диагонали матрицы равна: {}'.format(sum(sum(s))))

Сумма значений на диагонали матрицы равна: 105


# 3 Задание

Решите систему уравнений:

    4x + 2y + z = 4

    x + 3y = 12

    5y + 4z = -3

In [5]:
from numpy import linalg

In [6]:
f = np.array( [ [4,2,1], [1,3,0], [0,5,4] ] )
g = np.array( [4,12,-3] )
linalg.solve(f,g)

array([ 0.46666667,  3.84444444, -5.55555556])

# 4 Задание

In [7]:
import matplotlib.pyplot as plt

In [8]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [14]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [45]:
def cosine( a, b ):
    a_Length = np.linalg.norm(a)
    b_Length = np.linalg.norm(b)
    for i in a:
        return np.dot(a, b) / (a_Length * b_Length )
    
cosine(users_stats, next_user_stats)

array([0.04688072, 0.23440362, 0.09376145, 0.23440362, 0.09376145,
       0.        , 0.        , 0.14064217, 0.        , 0.        ])